<?xml version="1.0" encoding="UTF-8"?>
<definitions name="jdbcVendor" targetNamespace="http://j2ee.netbeans.org/wsdl/GetVendorURL/src/jdbcVendor" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://j2ee.netbeans.org/xsd/tableSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://j2ee.netbeans.org/wsdl/GetVendorURL/src/jdbcVendor" xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/">
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/">
            <xsd:import namespace="http://j2ee.netbeans.org/xsd/tableSchema" schemaLocation="jdbcVendor.xsd"/>
	</xsd:schema>
  </types>
  <message name="outputMsg">
    <part name="part" element="ns:jdbcVendor_Response"/>
  </message>
  <message name="inputMsg">
    <part name="part" element="ns:jdbcVendor_Request"/>
  </message>
  <portType name="jdbcPortType">
    <operation name="get_vendor">
      <input name="input" message="tns:inputMsg"/>
      <output name="output" message="tns:outputMsg"/>
    </operation>
  </portType>
  <binding name="binding" type="tns:jdbcPortType">
    <jdbc:binding xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/"/>
    <operation name="get_vendor">
    <jdbc:operation xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/"/>
      <input name="input">
    <jdbc:input xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/" MarkColumnName="" MarkColumnValue="" MoveRowToTableName="" PKName="" PollMilliSeconds="5000" PollingPostProcessing="MoveRow" TableName="jdbcVendor" Transaction="NOTransaction" numberOfRecords="" operationType="jdbcVendor_Operation" paramOrder="vendorName,opName" sql="SELECT test_seq_step.harness_url FROM vendor, vendor_test_sequences, test_sequence, test_seq_step WHERE vendor.name = ? AND vendor_test_sequences.vendor_id = vendor.vendor_id AND test_sequence.test_sequence_id = vendor_test_sequences.test_sequence_id AND test_seq_step.test_sequence_id = test_sequence.test_sequence_id AND test_sequence.type = 'standalone' AND test_sequence.name = ?"/>
      </input>
      <output name="output">
    <jdbc:output xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/" returnPartName="part"/>
      </output>
    </operation>
  </binding>
  <service name="service">
    <port name="port" binding="tns:binding">
    <jdbc:address xmlns:jdbc="http://schemas.sun.com/jbi/wsdl-extensions/jdbc/" jndiName="interop"/>
    </port>
  </service>
    <plink:partnerLinkType xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="jdbcpartner">
        <plink:role name="jdbcPortTypeRole" portType="tns:jdbcPortType"/>
    </plink:partnerLinkType>
</definitions>
