<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="GetDERGroupStatusesWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/GetDERGroupStatusesWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/GetDERGroupStatusesWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://www.epri.com/GetDERGroupStatuses">
    <import location="file:/usr/local/git/nrel/61968/wsdl/GetDERGroupStatuses.wsdl" namespace="http://www.epri.com/GetDERGroupStatuses"/>
    <plnk:partnerLinkType name="GetDERGroupStatuses_PortLinkType">
        <plnk:role name="GetDERGroupStatuses_PortRole" portType="ns:GetDERGroupStatuses_Port"/>
    </plnk:partnerLinkType>
</definitions>
