<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions name="GetMaintOrderService" targetNamespace="http://ws.server.sixthc.com/" xmlns:ns1="http://iec.ch/TC57/2015/GetMaintenanceOrders" xmlns:ns3="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.server.sixthc.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import location="http://localhost:8080/epriConnect/MaintOrderServiceGet?wsdl=GetMaintenanceOrders_Port.wsdl" namespace="http://iec.ch/TC57/2015/GetMaintenanceOrders">
    </wsdl:import>
  <wsdl:binding name="GetMaintOrderServiceSoapBinding" type="ns1:GetMaintenanceOrders_Port">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="GetMaintenanceOrders">
      <soap:operation soapAction="http://iec.ch/TC57/2015/GetMaintenanceOrders/GetMaintenanceOrders" style="document"/>
      <wsdl:input name="GetMaintenanceOrders">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="GetMaintenanceOrdersResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="GetMaintenanceOrdersFaultMessage">
        <soap:fault name="GetMaintenanceOrdersFaultMessage" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="GetMaintOrderService">
    <wsdl:port binding="tns:GetMaintOrderServiceSoapBinding" name="GetMaintOrderPort">      
      <soap:address location="${ENDPOINT_GET}"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>