<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions name="ExecuteMaintOrderCreateService" targetNamespace="http://ws.server.sixthc.com/" xmlns:ns1="http://iec.ch/TC57/2015/ExecuteMaintenanceOrders" xmlns:ns3="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.server.sixthc.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import location="http://localhost:8080/epriConnect/MaintOrderServiceCreate?wsdl=MaintenanceOrders_Port.wsdl" namespace="http://iec.ch/TC57/2015/ExecuteMaintenanceOrders">
    </wsdl:import>
  <wsdl:binding name="ExecuteMaintOrderCreateServiceSoapBinding" type="ns1:MaintenanceOrders_Port">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="CreateMaintenanceOrders">
      <soap:operation soapAction="http://iec.ch/TC57/2015/MaintenanceOrders/CreateMaintenanceOrders" style="document"/>
      <wsdl:input name="CreateMaintenanceOrders">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="CreateMaintenanceOrdersResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="FaultMessage">
        <soap:fault name="FaultMessage" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ExecuteMaintOrderCreateService">
    <wsdl:port binding="tns:ExecuteMaintOrderCreateServiceSoapBinding" name="ExecuteMaintOrderCreatePort">
      <soap:address location="${CreateMaintOrderAppServicePoint}"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>