<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions name="MaintenanceOrders_Port" targetNamespace="http://iec.ch/TC57/2015/ExecuteMaintenanceOrders" xmlns:ns1="http://iec.ch/TC57/2015/ExecuteMaintenanceOrders" xmlns:ns2="http://iec.ch/TC57/2015/MaintenanceOrdersMessage" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
<xs:schema elementFormDefault="qualified" targetNamespace="http://iec.ch/TC57/2015/MaintenanceOrdersMessage" version="1.0" xmlns:ns1="http://iec.ch/TC57/2011/schema/message" xmlns:ns2="http://iec.ch/TC57/2015/MaintenanceOrders#" xmlns:tns="http://iec.ch/TC57/2015/MaintenanceOrdersMessage" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:import namespace="http://iec.ch/TC57/2011/schema/message"/>
<xs:import namespace="http://iec.ch/TC57/2015/MaintenanceOrders#"/>
<xs:element name="CancelMaintenanceOrders" type="tns:MaintenanceOrdersRequestMessageType"/>
<xs:element name="CanceledMaintenanceOrders" type="tns:MaintenanceOrdersEventMessageType"/>
<xs:element name="ChangeMaintenanceOrders" type="tns:MaintenanceOrdersRequestMessageType"/>
<xs:element name="ChangedMaintenanceOrders" type="tns:MaintenanceOrdersEventMessageType"/>
<xs:element name="CloseMaintenanceOrders" type="tns:MaintenanceOrdersRequestMessageType"/>
<xs:element name="ClosedMaintenanceOrders" type="tns:MaintenanceOrdersEventMessageType"/>
<xs:element name="CreateMaintenanceOrders" type="tns:MaintenanceOrdersRequestMessageType"/>
<xs:element name="CreatedMaintenanceOrders" type="tns:MaintenanceOrdersEventMessageType"/>
<xs:element name="DeleteMaintenanceOrders" type="tns:MaintenanceOrdersRequestMessageType"/>
<xs:element name="DeletedMaintenanceOrders" type="tns:MaintenanceOrdersEventMessageType"/>
<xs:element name="MaintenanceOrdersFaultMessage" type="tns:MaintenanceOrdersFaultMessageType"/>
<xs:element name="MaintenanceOrdersResponseMessage" type="tns:MaintenanceOrdersResponseMessageType"/>
<xs:complexType name="MaintenanceOrdersRequestMessageType">
    <xs:sequence>
      <xs:element name="Header" type="ns1:HeaderType"/>
      <xs:element minOccurs="0" name="Request" type="ns1:RequestType"/>
      <xs:element minOccurs="0" name="Payload" type="tns:MaintenanceOrdersPayloadType"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="MaintenanceOrdersPayloadType">
    <xs:sequence>
      <xs:element ref="ns2:MaintenanceOrders"/>
      <xs:element minOccurs="0" name="OperationSet" type="ns1:OperationSet"/>
      <xs:element minOccurs="0" name="Compressed" type="xs:string"/>
      <xs:element minOccurs="0" name="Format" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="MaintenanceOrdersResponseMessageType">
    <xs:sequence>
      <xs:element name="Header" type="ns1:HeaderType"/>
      <xs:element name="Reply" type="ns1:ReplyType"/>
      <xs:element minOccurs="0" name="Payload" type="tns:MaintenanceOrdersPayloadType"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="MaintenanceOrdersFaultMessageType">
    <xs:sequence>
      <xs:element name="Reply" type="ns1:ReplyType"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="MaintenanceOrdersEventMessageType">
    <xs:sequence>
      <xs:element name="Header" type="ns1:HeaderType"/>
      <xs:element minOccurs="0" name="Payload" type="tns:MaintenanceOrdersPayloadType"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
<xs:schema targetNamespace="http://iec.ch/TC57/2015/MaintenanceOrders#" version="1.0" xmlns:tns="http://iec.ch/TC57/2015/MaintenanceOrders#" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="MaintenanceOrders" type="tns:MaintenanceOrders"/>
<xs:complexType name="MaintenanceOrders">
    <xs:sequence>
      <xs:element form="qualified" maxOccurs="unbounded" name="MaintenanceOrder" type="tns:MaintenanceOrder"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="MaintenanceOrder">
    <xs:sequence>
      <xs:element form="qualified" minOccurs="0" name="mRID" type="xs:string"/>
      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="Names" type="tns:Name"/>
      <xs:element form="qualified" minOccurs="0" name="Organisation" type="tns:Organisation"/>
      <xs:element form="qualified" maxOccurs="unbounded" name="Work" type="tns:Work"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="Name">
    <xs:sequence>
      <xs:element form="qualified" name="name" type="xs:string"/>
      <xs:element form="qualified" minOccurs="0" name="NameType" type="tns:NameType"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="NameType">
    <xs:sequence>
      <xs:element form="qualified" minOccurs="0" name="description" type="xs:string"/>
      <xs:element form="qualified" name="name" type="xs:string"/>
      <xs:element form="qualified" minOccurs="0" name="NameTypeAuthority" type="tns:NameTypeAuthority"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="NameTypeAuthority">
    <xs:sequence>
      <xs:element form="qualified" minOccurs="0" name="description" type="xs:string"/>
      <xs:element form="qualified" name="name" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="Organisation">
    <xs:sequence>
      <xs:element form="qualified" minOccurs="0" name="mRID" type="xs:string"/>
      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="Names" type="tns:Name"/>
      <xs:element form="qualified" minOccurs="0" name="phone1">
        <xs:complexType>
          <xs:sequence>
            <xs:element form="qualified" minOccurs="0" name="areaCode" type="xs:string"/>
            <xs:element form="qualified" minOccurs="0" name="cityCode" type="xs:string"/>
            <xs:element form="qualified" minOccurs="0" name="countryCode" type="xs:string"/>
            <xs:element form="qualified" minOccurs="0" name="extension" type="xs:string"/>
            <xs:element form="qualified" name="localNumber" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element form="qualified" minOccurs="0" name="streetAddress">
        <xs:complexType>
          <xs:sequence>
            <xs:element form="qualified" name="streetDetail">
              <xs:complexType>
                <xs:sequence>
                  <xs:element form="qualified" name="addressGeneral" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="buildingName" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="code" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="name" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="number" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="prefix" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="suffix" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="suiteNumber" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="type" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="withinTownLimits" type="xs:boolean"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element form="qualified" name="townDetail">
              <xs:complexType>
                <xs:sequence>
                  <xs:element form="qualified" minOccurs="0" name="code" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="country" type="xs:string"/>
                  <xs:element form="qualified" name="name" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="section" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="stateOrProvince" type="xs:string"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="Work">
    <xs:sequence>
      <xs:element form="qualified" minOccurs="0" name="mRID" type="xs:string"/>
      <xs:element form="qualified" name="kind" type="tns:WorkKind"/>
      <xs:element form="qualified" minOccurs="0" name="lastModifiedDateTime" type="xs:dateTime"/>
      <xs:element form="qualified" minOccurs="0" name="requestDateTime" type="xs:dateTime"/>
      <xs:element form="qualified" name="statusKind" type="tns:WorkStatusKind"/>
      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="ActivityRecords" type="tns:ActivityRecord"/>
      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="Names" type="tns:Name"/>
      <xs:element form="qualified" minOccurs="0" name="priority">
        <xs:complexType>
          <xs:sequence>
            <xs:element form="qualified" minOccurs="0" name="justification" type="xs:string"/>
            <xs:element form="qualified" name="rank" type="xs:integer"/>
            <xs:element form="qualified" minOccurs="0" name="type" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="TimeSchedules" type="tns:WorkTimeSchedule"/>
      <xs:element form="qualified" minOccurs="0" name="WorkLocation" type="tns:WorkLocation"/>
      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="WorkTasks" type="tns:WorkTask"/>
      <xs:element form="qualified" minOccurs="0" name="Attachments">
        <xs:complexType>
          <xs:sequence>
            <xs:element form="qualified" maxOccurs="unbounded" name="Attachment" type="tns:Attachment"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="ActivityRecord">
    <xs:sequence>
      <xs:element form="qualified" name="createdDateTime" type="xs:dateTime"/>
      <xs:element form="qualified" minOccurs="0" name="reason" type="xs:string"/>
      <xs:element form="qualified" minOccurs="0" name="severity" type="xs:string"/>
      <xs:element form="qualified" name="type" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="WorkTimeSchedule">
    <xs:sequence>
      <xs:element form="qualified" name="kind" type="tns:WorkTimeScheduleKind"/>
      <xs:element form="qualified" name="scheduleInterval">
        <xs:complexType>
          <xs:sequence>
            <xs:element form="qualified" minOccurs="0" name="end" type="xs:dateTime"/>
            <xs:element form="qualified" minOccurs="0" name="start" type="xs:dateTime"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="WorkLocation">
    <xs:sequence>
      <xs:element form="qualified" minOccurs="0" name="mRID" type="xs:string"/>
      <xs:element form="qualified" minOccurs="0" name="direction" type="xs:string"/>
      <xs:element form="qualified" minOccurs="0" name="CoordinateSystem">
        <xs:complexType>
          <xs:sequence>
            <xs:element form="qualified" name="crsUrn" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="Hazards" type="tns:AssetLocationHazard"/>
      <xs:element form="qualified" minOccurs="0" name="InternalLocation" type="tns:InternalLocation"/>
      <xs:element form="qualified" minOccurs="0" name="mainAddress">
        <xs:complexType>
          <xs:sequence>
            <xs:element form="qualified" name="streetDetail">
              <xs:complexType>
                <xs:sequence>
                  <xs:element form="qualified" name="addressGeneral" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="addressGeneral2" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="addressGeneral3" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="buildingName" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="code" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="name" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="number" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="prefix" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="suffix" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="suiteNumber" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="type" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="withinTownLimits" type="xs:boolean"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element form="qualified" name="townDetail">
              <xs:complexType>
                <xs:sequence>
                  <xs:element form="qualified" minOccurs="0" name="code" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="country" type="xs:string"/>
                  <xs:element form="qualified" name="name" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="section" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="stateOrProvince" type="xs:string"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="Names" type="tns:Name"/>
      <xs:element form="qualified" minOccurs="0" name="phone1" type="tns:TelephoneNumber"/>
      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="PositionPoints">
        <xs:complexType>
          <xs:sequence>
            <xs:element form="qualified" minOccurs="0" name="sequenceNumber" type="xs:integer"/>
            <xs:element form="qualified" name="xPosition" type="xs:string"/>
            <xs:element form="qualified" name="yPosition" type="xs:string"/>
            <xs:element form="qualified" minOccurs="0" name="zPosition" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="AssetLocationHazard">
    <xs:sequence>
      <xs:element form="qualified" name="type" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="InternalLocation">
    <xs:sequence>
      <xs:element form="qualified" minOccurs="0" name="BuildingName" type="xs:string"/>
      <xs:element form="qualified" name="BuildingNumber" type="xs:string"/>
      <xs:element form="qualified" name="Floor" type="xs:string"/>
      <xs:element form="qualified" name="RoomNumber" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="TelephoneNumber">
    <xs:sequence>
      <xs:element form="qualified" minOccurs="0" name="areaCode" type="xs:string"/>
      <xs:element form="qualified" minOccurs="0" name="cityCode" type="xs:string"/>
      <xs:element form="qualified" minOccurs="0" name="countryCode" type="xs:string"/>
      <xs:element form="qualified" minOccurs="0" name="extension" type="xs:string"/>
      <xs:element form="qualified" name="localNumber" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="WorkTask">
    <xs:sequence>
      <xs:element form="qualified" minOccurs="0" name="mRID" type="xs:string"/>
      <xs:element form="qualified" minOccurs="0" name="crewETA" type="xs:dateTime"/>
      <xs:element form="qualified" minOccurs="0" name="instruction" type="xs:string"/>
      <xs:element form="qualified" name="statusKind" type="tns:WorkStatusKind"/>
      <xs:element form="qualified" name="subject" type="xs:string"/>
      <xs:element form="qualified" name="taskKind" type="tns:WorkTaskKind"/>
      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="Assets" type="tns:Asset"/>
      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="Crews" type="tns:Crew"/>
      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="MaterialItems">
        <xs:complexType>
          <xs:sequence>
            <xs:element form="qualified" minOccurs="0" name="mRID" type="xs:string"/>
            <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="Names" type="tns:Name"/>
            <xs:element form="qualified" minOccurs="0" name="quantity">
              <xs:complexType>
                <xs:sequence>
                  <xs:element form="qualified" minOccurs="0" name="multiplier" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="unit" type="xs:string"/>
                  <xs:element form="qualified" name="value" type="xs:integer"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="Names" type="tns:Name"/>
      <xs:element form="qualified" minOccurs="0" name="OldAsset" type="tns:Asset"/>
      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="TimeSchedules" type="tns:WorkTimeSchedule"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="Asset">
    <xs:sequence>
      <xs:element form="qualified" minOccurs="0" name="mRID" type="xs:string"/>
      <xs:element form="qualified" name="critical" type="xs:boolean"/>
      <xs:element form="qualified" name="utcNumber" type="xs:string"/>
      <xs:element form="qualified" minOccurs="0" name="Location" type="tns:WorkLocation"/>
      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="Names" type="tns:Name"/>
      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="Procedures">
        <xs:complexType>
          <xs:sequence>
            <xs:element form="qualified" name="instruction" type="xs:string"/>
            <xs:element form="qualified" name="kind" type="tns:ProcedureKind"/>
            <xs:element form="qualified" minOccurs="0" name="sequenceNumber" type="xs:string"/>
            <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="Measurements">
              <xs:complexType>
                <xs:sequence>
                  <xs:element form="qualified" minOccurs="0" name="measurementType" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="phases" type="tns:PhaseCode"/>
                  <xs:element form="qualified" minOccurs="0" name="unitMultiplier" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="unitSymbol" type="xs:string"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="Crew">
    <xs:sequence>
      <xs:element form="qualified" minOccurs="0" name="mRID" type="xs:string"/>
      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="CrewMembers" type="tns:CrewMember"/>
      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="Names" type="tns:Name"/>
      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="WorkAssets" type="tns:WorkAsset"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="CrewMember">
    <xs:sequence>
      <xs:element form="qualified" name="Person">
        <xs:complexType>
          <xs:sequence>
            <xs:element form="qualified" minOccurs="0" name="firstName" type="xs:string"/>
            <xs:element form="qualified" name="lastName" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="WorkAsset">
    <xs:sequence>
      <xs:element form="qualified" minOccurs="0" name="mRID" type="xs:string"/>
      <xs:element form="qualified" name="critical" type="xs:boolean"/>
      <xs:element form="qualified" minOccurs="0" name="lastCalibrationDate" type="xs:date"/>
      <xs:element form="qualified" minOccurs="0" name="odometerReadDateTime" type="xs:dateTime"/>
      <xs:element form="qualified" minOccurs="0" name="odometerReading" type="xs:float"/>
      <xs:element form="qualified" minOccurs="0" name="usageKind" type="tns:VehicleUsageKind"/>
      <xs:element form="qualified" name="utcNumber" type="xs:string"/>
      <xs:element form="qualified" minOccurs="0" name="Location" type="tns:WorkLocation"/>
      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="Names" type="tns:Name"/>
      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="Procedures">
        <xs:complexType>
          <xs:sequence>
            <xs:element form="qualified" name="instruction" type="xs:string"/>
            <xs:element form="qualified" minOccurs="0" name="kind" type="tns:ProcedureKind"/>
            <xs:element form="qualified" minOccurs="0" name="sequenceNumber" type="xs:string"/>
            <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="Measurements">
              <xs:complexType>
                <xs:sequence>
                  <xs:element form="qualified" minOccurs="0" name="measurementType" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="phases" type="tns:PhaseCode"/>
                  <xs:element form="qualified" minOccurs="0" name="unitMultiplier" type="xs:string"/>
                  <xs:element form="qualified" minOccurs="0" name="unitSymbol" type="xs:string"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="Attachment">
    <xs:sequence>
      <xs:element form="qualified" minOccurs="0" name="Comment" type="xs:string"/>
      <xs:element form="qualified" minOccurs="0" name="Description" type="xs:string"/>
      <xs:element form="qualified" name="Url" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
<xs:simpleType name="WorkKind">
    <xs:restriction base="xs:string">
      <xs:enumeration value="connect"/>
      <xs:enumeration value="construction"/>
      <xs:enumeration value="disconnect"/>
      <xs:enumeration value="inspection"/>
      <xs:enumeration value="maintenance"/>
      <xs:enumeration value="other"/>
      <xs:enumeration value="reconnect"/>
      <xs:enumeration value="repair"/>
      <xs:enumeration value="service"/>
      <xs:enumeration value="test"/>
    </xs:restriction>
  </xs:simpleType>
<xs:simpleType name="WorkStatusKind">
    <xs:restriction base="xs:string">
      <xs:enumeration value="approved"/>
      <xs:enumeration value="cancelled"/>
      <xs:enumeration value="closed"/>
      <xs:enumeration value="completed"/>
      <xs:enumeration value="dispatched"/>
      <xs:enumeration value="enroute"/>
      <xs:enumeration value="inProgress"/>
      <xs:enumeration value="onSite"/>
      <xs:enumeration value="scheduled"/>
      <xs:enumeration value="waitingOnApproval"/>
      <xs:enumeration value="waitingOnMaterial"/>
      <xs:enumeration value="waitingToBeScheduled"/>
    </xs:restriction>
  </xs:simpleType>
<xs:simpleType name="WorkTimeScheduleKind">
    <xs:restriction base="xs:string">
      <xs:enumeration value="actual"/>
      <xs:enumeration value="earliest"/>
      <xs:enumeration value="estimate"/>
      <xs:enumeration value="latest"/>
      <xs:enumeration value="request"/>
    </xs:restriction>
  </xs:simpleType>
<xs:simpleType name="WorkTaskKind">
    <xs:restriction base="xs:string">
      <xs:enumeration value="exchange"/>
      <xs:enumeration value="install"/>
      <xs:enumeration value="investigate"/>
      <xs:enumeration value="remove"/>
    </xs:restriction>
  </xs:simpleType>
<xs:simpleType name="ProcedureKind">
    <xs:restriction base="xs:string">
      <xs:enumeration value="diagnosis"/>
      <xs:enumeration value="inspection"/>
      <xs:enumeration value="maintenance"/>
      <xs:enumeration value="other"/>
      <xs:enumeration value="test"/>
    </xs:restriction>
  </xs:simpleType>
<xs:simpleType name="PhaseCode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="A"/>
      <xs:enumeration value="AB"/>
      <xs:enumeration value="ABC"/>
      <xs:enumeration value="ABCN"/>
      <xs:enumeration value="ABN"/>
      <xs:enumeration value="AC"/>
      <xs:enumeration value="ACN"/>
      <xs:enumeration value="AN"/>
      <xs:enumeration value="B"/>
      <xs:enumeration value="BC"/>
      <xs:enumeration value="BCN"/>
      <xs:enumeration value="BN"/>
      <xs:enumeration value="C"/>
      <xs:enumeration value="CN"/>
      <xs:enumeration value="N"/>
      <xs:enumeration value="none"/>
      <xs:enumeration value="s1"/>
      <xs:enumeration value="s12"/>
      <xs:enumeration value="s12N"/>
      <xs:enumeration value="s1N"/>
      <xs:enumeration value="s2"/>
      <xs:enumeration value="s2N"/>
    </xs:restriction>
  </xs:simpleType>
<xs:simpleType name="VehicleUsageKind">
    <xs:restriction base="xs:string">
      <xs:enumeration value="contractor"/>
      <xs:enumeration value="crew"/>
      <xs:enumeration value="other"/>
      <xs:enumeration value="user"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>
<xs:schema elementFormDefault="qualified" targetNamespace="http://iec.ch/TC57/2011/schema/message" version="1.0" xmlns:tns="http://iec.ch/TC57/2011/schema/message" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="EventMessage" type="tns:EventMessageType"/>
<xs:element name="FaultMessage" type="tns:FaultMessageType"/>
<xs:element name="Message" type="tns:MessageType"/>
<xs:element name="RequestMessage" type="tns:RequestMessageType"/>
<xs:element name="ResponseMessage" type="tns:ResponseMessageType"/>
<xs:complexType name="HeaderType">
    <xs:sequence>
      <xs:element name="Verb" type="xs:string"/>
      <xs:element name="Noun" type="xs:string"/>
      <xs:element minOccurs="0" name="Revision" type="xs:string"/>
      <xs:element minOccurs="0" name="ReplayDetection" type="tns:ReplayDetectionType"/>
      <xs:element minOccurs="0" name="Context" type="xs:string"/>
      <xs:element minOccurs="0" name="Timestamp" type="xs:dateTime"/>
      <xs:element minOccurs="0" name="Source" type="xs:string"/>
      <xs:element minOccurs="0" name="AsyncReplyFlag" type="xs:boolean"/>
      <xs:element minOccurs="0" name="ReplyAddress" type="xs:string"/>
      <xs:element minOccurs="0" name="AckRequired" type="xs:boolean"/>
      <xs:element minOccurs="0" name="User" type="tns:UserType"/>
      <xs:element minOccurs="0" name="MessageID" type="xs:string"/>
      <xs:element minOccurs="0" name="CorrelationID" type="xs:string"/>
      <xs:element minOccurs="0" name="Comment" type="xs:string"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="Property" type="tns:MessageProperty"/>
      <xs:any maxOccurs="unbounded" minOccurs="0" namespace="##other" processContents="lax"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="ReplayDetectionType">
    <xs:sequence>
      <xs:element name="Nonce" type="xs:string"/>
      <xs:element name="Created" type="xs:dateTime"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="UserType">
    <xs:sequence>
      <xs:element name="UserID" type="xs:string"/>
      <xs:element minOccurs="0" name="Organization" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="MessageProperty">
    <xs:sequence>
      <xs:element name="Name" type="xs:string"/>
      <xs:element minOccurs="0" name="Value" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="ResponseMessageType">
    <xs:sequence>
      <xs:element name="Header" type="tns:HeaderType"/>
      <xs:element name="Reply" type="tns:ReplyType"/>
      <xs:element minOccurs="0" name="Payload" type="tns:PayloadType"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="ReplyType">
    <xs:sequence>
      <xs:element name="Result" type="xs:string"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="Error" type="tns:ErrorType"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="ID">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="idType" type="xs:string"/>
              <xs:attribute name="idAuthority" type="xs:string"/>
              <xs:attribute name="kind" type="tns:IDKindType"/>
              <xs:attribute name="objectType" type="xs:string"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:any maxOccurs="unbounded" minOccurs="0" namespace="##other" processContents="lax"/>
      <xs:element minOccurs="0" name="operationId" type="xs:integer"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="ErrorType">
    <xs:sequence>
      <xs:element name="code" type="xs:string"/>
      <xs:element minOccurs="0" name="level" type="xs:string"/>
      <xs:element minOccurs="0" name="reason" type="xs:string"/>
      <xs:element minOccurs="0" name="details" type="xs:string"/>
      <xs:element minOccurs="0" name="xpath" type="xs:QName"/>
      <xs:element minOccurs="0" name="stackTrace" type="xs:string"/>
      <xs:element minOccurs="0" name="Location" type="tns:LocationType"/>
      <xs:element minOccurs="0" name="ID">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="idType" type="xs:string"/>
              <xs:attribute name="idAuthority" type="xs:string"/>
              <xs:attribute name="kind" type="tns:IDKindType"/>
              <xs:attribute name="objectType" type="xs:string"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="0" name="relatedID">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="idType" type="xs:string"/>
              <xs:attribute name="idAuthority" type="xs:string"/>
              <xs:attribute name="kind" type="tns:IDKindType"/>
              <xs:attribute name="objectType" type="xs:string"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="0" name="object" type="tns:ObjectType"/>
      <xs:element minOccurs="0" name="operationId" type="xs:integer"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="LocationType">
    <xs:sequence>
      <xs:element minOccurs="0" name="node" type="xs:string"/>
      <xs:element minOccurs="0" name="pipeline" type="xs:string"/>
      <xs:element minOccurs="0" name="stage" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="ObjectType">
    <xs:sequence>
      <xs:element minOccurs="0" name="mRID" type="xs:string"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="Name" type="tns:Name"/>
      <xs:element minOccurs="0" name="objectType" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="Name">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element minOccurs="0" name="NameType" type="tns:NameType"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="NameType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element minOccurs="0" name="description" type="xs:string"/>
      <xs:element minOccurs="0" name="NameTypeAuthority" type="tns:NameTypeAuthority"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="NameTypeAuthority">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element minOccurs="0" name="description" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="PayloadType">
    <xs:sequence>
      <xs:any maxOccurs="unbounded" minOccurs="0" namespace="##other" processContents="skip"/>
      <xs:element minOccurs="0" name="OperationSet" type="tns:OperationSet"/>
      <xs:element minOccurs="0" name="Compressed" type="xs:string"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="ID">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="idType" type="xs:string"/>
              <xs:attribute name="idAuthority" type="xs:string"/>
              <xs:attribute name="kind" type="tns:IDKindType"/>
              <xs:attribute name="objectType" type="xs:string"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="0" name="Format" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="OperationSet">
    <xs:sequence>
      <xs:element minOccurs="0" name="enforceMsgSequence" type="xs:boolean"/>
      <xs:element minOccurs="0" name="enforceTransactionalIntegrity" type="xs:boolean"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="Operation" type="tns:OperationType"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="OperationType">
    <xs:sequence>
      <xs:element name="operationId" type="xs:integer"/>
      <xs:element minOccurs="0" name="noun" type="xs:string"/>
      <xs:element minOccurs="0" name="verb" type="xs:string"/>
      <xs:element default="false" minOccurs="0" name="elementOperation" type="xs:boolean"/>
      <xs:any namespace="##other" processContents="skip"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="FaultMessageType">
    <xs:sequence>
      <xs:element name="Reply" type="tns:ReplyType"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="OptionType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element minOccurs="0" name="value" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="RequestType">
    <xs:sequence>
      <xs:element minOccurs="0" name="StartTime" type="xs:dateTime"/>
      <xs:element minOccurs="0" name="EndTime" type="xs:dateTime"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="Option" type="tns:OptionType"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="ID">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="idType" type="xs:string"/>
              <xs:attribute name="idAuthority" type="xs:string"/>
              <xs:attribute name="kind" type="tns:IDKindType"/>
              <xs:attribute name="objectType" type="xs:string"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:any maxOccurs="unbounded" minOccurs="0" namespace="##other" processContents="lax"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="EventMessageType">
    <xs:sequence>
      <xs:element name="Header" type="tns:HeaderType"/>
      <xs:element minOccurs="0" name="Payload" type="tns:PayloadType"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="RequestMessageType">
    <xs:sequence>
      <xs:element name="Header" type="tns:HeaderType"/>
      <xs:element minOccurs="0" name="Request" type="tns:RequestType"/>
      <xs:element minOccurs="0" name="Payload" type="tns:PayloadType"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="MessageType">
    <xs:sequence>
      <xs:element name="Header" type="tns:HeaderType"/>
      <xs:element minOccurs="0" name="Request" type="tns:RequestType"/>
      <xs:element minOccurs="0" name="Reply" type="tns:ReplyType"/>
      <xs:element minOccurs="0" name="Payload" type="tns:PayloadType"/>
    </xs:sequence>
  </xs:complexType>
<xs:simpleType name="IDKindType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="name"/>
      <xs:enumeration value="uuid"/>
      <xs:enumeration value="transaction"/>
      <xs:enumeration value="other"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>
  </wsdl:types>
  <wsdl:message name="FaultMessage">
    <wsdl:part element="ns2:MaintenanceOrdersFaultMessage" name="FaultMessage">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="CreateMaintenanceOrders">
    <wsdl:part element="ns2:CreateMaintenanceOrders" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="CreateMaintenanceOrdersResponse">
    <wsdl:part element="ns2:MaintenanceOrdersResponseMessage" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="MaintenanceOrders_Port">
    <wsdl:operation name="CreateMaintenanceOrders">
      <wsdl:input message="ns1:CreateMaintenanceOrders" name="CreateMaintenanceOrders">
    </wsdl:input>
      <wsdl:output message="ns1:CreateMaintenanceOrdersResponse" name="CreateMaintenanceOrdersResponse">
    </wsdl:output>
      <wsdl:fault message="ns1:FaultMessage" name="FaultMessage">
    </wsdl:fault>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>