<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="GetMaintenanceOrdersWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/GetMaintenanceOrdersWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/GetMaintenanceOrdersWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://iec.ch/TC57/2015/GetMaintenanceOrders">
    <import location="GetDyn/GetMaintenanceOrders.wsdl" namespace="http://iec.ch/TC57/2015/GetMaintenanceOrders"/>
    <plnk:partnerLinkType name="GetMaintenanceOrders_PortLinkType">
        <plnk:role name="GetMaintenanceOrders_PortRole" portType="ns:GetMaintenanceOrders_Port"/>
    </plnk:partnerLinkType>
</definitions>
