<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ExecuteDERGroupDispatchesIn" targetNamespace="http://enterprise.netbeans.org/bpel/ExecuteDERGroupDispatchesIn" xmlns:tns="http://enterprise.netbeans.org/bpel/ExecuteDERGroupDispatchesIn" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://www.epri.com/ExecuteDERGroupDispatches">
    <import location="file:/usr/local/git/nrel/61968/wsdl/ExecuteDERGroupDispatches.wsdl" namespace="http://www.epri.com/ExecuteDERGroupDispatches"/>
    <plnk:partnerLinkType name="DERGroupDispatches_PortLinkType">
        <plnk:role name="DERGroupDispatches_PortRole" portType="ns:DERGroupDispatches_Port"/>
    </plnk:partnerLinkType>
</definitions>
