<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:tns="http://www.epri.com/2016/ExecuteDERGroups" 
xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" 
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:wsi="http://ws-i.org/schemas/conformanceClaim/" 
xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" 
xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" 
xmlns:infoMessage="http://www.epri.com/2016/DERGroupsMessage" name="ExecuteDERGroups" targetNamespace="http://www.epri.com/2016/ExecuteDERGroups">
<xs:annotation>
	<xs:documentation>
	// Copyright (c) 2016, Electric Power Research Institute
// All rights reserved
// Redistribution and use in source and bunary forms, with or without modification, are permitted provided that the following conditions are met:
// 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the aboev copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
// 3. Neither the name of the copyright holder nor the name of its contributors may be used to endorse or promote products derived from this software without specific prior written permission
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRENTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRENTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THISE SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
	</xs:documentation>
</xs:annotation>
	<wsdl:types>
		<xs:schema targetNamespace="http://www.epri.com/2016/ExecuteDERGroups" elementFormDefault="qualified">
			<xs:import namespace="http://www.epri.com/2016/DERGroupsMessage" schemaLocation="xsd/DERGroupsMessage.xsd"/>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="CreateDERGroupsRequestMessage">
		<wsdl:part name="CreateDERGroupsRequestMessage" element="infoMessage:CreateDERGroups"/>
	</wsdl:message>
	<wsdl:message name="ResponseMessage">
		<wsdl:part name="ResponseMessage" element="infoMessage:DERGroupsResponseMessage"/>
	</wsdl:message>
	<wsdl:message name="FaultMessage">
		<wsdl:part name="FaultMessage" element="infoMessage:DERGroupsFaultMessage"/>
	</wsdl:message>
	<wsdl:portType name="DERGroups_Port">
		<wsdl:operation name="CreateDERGroups">
			<wsdl:input name="CreateDERGroupsRequest" message="tns:CreateDERGroupsRequestMessage"/>
			<wsdl:output name="CreateDERGroupsResponse" message="tns:ResponseMessage"/>
			<wsdl:fault name="CreateDERGroupsFault" message="tns:FaultMessage"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="DERGroups_Binding" type="tns:DERGroups_Port">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="CreateDERGroups">
			<soap:operation soapAction="http://www.epri.com/2016/DERGroups/CreateDERGroups" style="document"/>
			<wsdl:input name="CreateDERGroupsRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="CreateDERGroupsResponse">
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="CreateDERGroupsFault">
				<soap:fault name="CreateDERGroupsFault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ExecuteDERGroups">
		<wsdl:port name="DERGroups_Port" binding="tns:DERGroups_Binding">
			<soap:address location="http://www.epri.com/2016/ExecuteDERGroups"/>
		</wsdl:port>
	</wsdl:service>
	<xs:schema targetNamespace="http://www.epri.com/2016/ExecuteDERGroupsMessage" elementFormDefault="qualified">
		<xs:import namespace="http://www.epri.com/2016/DERGroupsMessage" schemaLocation="xsd/DERGroupsMessage.xsd"/>
		<!--<xs:include schemaLocation="xsd/MaintenanceOrdersMessage.xsd"/>-->
	</xs:schema>
	<!-- Message Definitions -->
	<!-- Port Definitions -->
</wsdl:definitions>
