<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="GetDERGroupWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/GetDERGroupWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/GetDERGroupWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://iec.ch/TC57/2011/GetDERGroup">
    <import location="file:/Users/BenGoodwin/git/opendms/DER/wsdl/GetDERGroup.wsdl" namespace="http://iec.ch/TC57/2011/GetDERGroup"/>
    <plnk:partnerLinkType name="GetDERGroup_PortLinkType">
        <plnk:role name="GetDERGroup_PortRole" portType="ns:GetDERGroup_Port"/>
    </plnk:partnerLinkType>
</definitions>
