<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="MaintOrderServiceGetWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/MaintOrderServiceGetWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/MaintOrderServiceGetWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://iec.ch/TC57/2015/GetMaintenanceOrders">
    <import location="http://localhost:8080/epriConnect/MaintOrderServiceGet?wsdl=GetMaintenanceOrders_Port.wsdl" namespace="http://iec.ch/TC57/2015/GetMaintenanceOrders"/>
    <import location="http://localhost:8080/epriConnect/MaintOrderServiceGet?wsdl" namespace="http://ws.server.sixthc.com/"/>
    <plnk:partnerLinkType name="GetMaintenanceOrders_PortLinkType">
        <plnk:role name="GetMaintenanceOrders_PortRole" portType="ns:GetMaintenanceOrders_Port"/>
    </plnk:partnerLinkType>
    <plnk:partnerLinkType name="GetMaintenanceOrdersR1">
        <plnk:role name="GetMaintenanceOrders_PortRole" portType="ns:GetMaintenanceOrders_Port"/>
    </plnk:partnerLinkType>
</definitions>
